### ISSUE TITLE
服务端无法正常关闭

### ISSUE THREAD

**Issue by Illusionika** [Chikage0o0/CreateOrigin#3]
只要服务器里进过人,再敲/stop最后会卡住不动关不掉,只能ctrl+c强制关闭进程 (刚开启没进人的服务端能直接自然关闭进程)

stop关不掉很烦,我有大量定时任务要在关服后进行,而且每次都是强关等于炸服早晚出事

**Comment by Chikage0o0** [comment]
实际上服务器已经保存了所有区块，所以强退也不会炸服。
原因已经查明，下个版本修复
