### ISSUE TITLE
请问一下每5分钟保存一次区块的是哪个mod?

### ISSUE THREAD

**Issue by Illusionika** [Chikage0o0/CreateOrigin#4]
5分钟太频繁了,玩家反映会经常顿卡.

这是哪个mod的功能?扫了一眼没识别出来.就是下图这个功能.

![111](https://user-images.githubusercontent.com/46653839/211955807-aa25dff2-1bd1-4942-8510-49e0cf557aae.png)

**Comment by Chikage0o0** [comment]
首先该问题并不是导致顿卡的原因，你应该使用carpet查看tps，再根据observable找到卡顿原因，如果无法解决请升级服务器配置。

该日志仅仅是https://github.com/Kneelawk/GraphLib打印的垃圾信息。该模组在0.3.3升级时删除了该垃圾信息。
GraphLib是Extended Drawers的依赖库，并集成在Extended Drawers中，如果你仅仅想不打印该垃圾信息，额外向mods文件夹添加GraphLib最新版即可。
