### ISSUE TITLE
利用梦境和玻璃传送门更改游戏模式

### ISSUE THREAD

**Issue by HoshinoTented** [Chikage0o0/CreateOrigin#5]
JRE：`jdk 20`
整合包版本：`v4.8.2`

在生存模式下进入梦境后，在梦中建造并激活玻璃传送门，进入虚无世界后再通过传送门回去后会回到主世界（而不是梦境世界），并且此时的游戏模式是创造模式。
在创造模式下进入梦境会变为生存模式。
我的存档开启了作弊，不知道是否与此有关。

**Comment by Chikage0o0** [comment]
最新的提交已经删除了梦境
