### ISSUE TITLE
请问5.0的计划是怎样的？

### ISSUE THREAD

**Issue by link-fgfgui** [Chikage0o0/CreateOrigin#6]
Create Fabric 1.20.1已[出](https://modrinth.com/mod/create-fabric/version/0.5.1-d-build.1161+mc1.20.1)
~~大概啥时候更新啊，出个Alpha也行啊~~

**Comment by Chikage0o0** [comment]
短时间内可能难以更新到1.20.1，具体还要看 createaddition Extra Alchemy Naturalist这三个mod何时更新

**Comment by Chikage0o0** [comment]
已经推送
